name = "StableDistributions"
uuid = "3756410d-ab6e-41a2-9897-9aa267a7ef31"
authors = ["Jakub Ślęzak <128084860+jaksle@users.noreply.github.com> and contributors"]
version = "1.0.2"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"

[compat]
Distributions = ">=0.20"
Random = "<0.0.1, 1"
QuadGK = "2"
SpecialFunctions = "1.2, 2"
StatsFuns = ">=0.9"
Test = "<0.0.1, 1"
Aqua = "0.8"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"

[targets]
test = ["Test", "Aqua"]
